/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qihoo360_test_JniSupport */

#ifndef _Included_com_qihoo360_test_JniSupport
#define _Included_com_qihoo360_test_JniSupport


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qihoo360_test_JniSupport
 * Method:    getCrashId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qihoo360_test_JniSupport_getCrashId(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_qihoo360_test_JniSupport_encrypt(JNIEnv *, jclass, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_qihoo360_test_JniSupport_decrypt(JNIEnv *, jclass, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_qihoo360_test_JniSupport_getBase64(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
